swagger: '2.0'
info:
  description: IFOOD challenge
  version: 0.0.1
  title: Backend challenge api
  contact:
    name: Filipe Torqueto
    email: filipe.torqueto@gmail.com
  license:
    name: Apache License Version 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0"'
host: 'localhost:8080'
basePath: /
tags:
  - name: playlist-controller
    description: Playlist Controller
paths:
  /playlist:
    get:
      tags:
        - playlist-controller
      summary: Given a city name or latitude and logitude, the API will return a music list based on the city temperature.
      operationId: returnPlaylistGivenPositionUsingGET
      produces:
        - '*/*'
      parameters:
        - name: cityName
          in: query
          description: cityName
          required: false
          type: string
        - name: lat
          in: query
          description: lat
          required: false
          type: string
        - name: lon
          in: query
          description: lon
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
